# Generated by Django 3.1.4 on 2025-11-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='componente',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Faça upload de uma imagem do componente', null=True, upload_to='componentes/'),
        ),
    ]
