# Generated by Django 3.1.4 on 2025-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251119_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='imagem',
        ),
        migrations.AddField(
            model_name='componente',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
