# Generated by Django 3.1.4 on 2025-11-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251119_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='video_youtube',
            field=models.CharField(blank=True, help_text='Link do vídeo do YouTube', max_length=500),
        ),
    ]
